[server]
host = "0.0.0.0"
port = 8080
api_key = ""
allow_no_api_key = true

[runtime]
type = "docker"
execd_image = "opensandbox/execd:v1.0.20"

[sandbox]
default_image = "opensandbox/code-interpreter:v1.1.0"